CIDADES_POR_ESTADO_MIN = 1
CIDADES_POR_ESTADO_MAX = 30

BAIRROS_POR_CIDADE_MIN = 1
BAIRROS_POR_CIDADE_MAX = 5

CONDUTORES_MIN = 500
CONDUTORES_MAX = 800

VEICULOS_MIN = 200
VEICULOS_MAX = 500
VEICULOS_INATIVO_CHANCE = 5
VEICULOS_BLOQUEADO_CHANCE = 10