CIDADES_POR_ESTADO_MIN = 1
CIDADES_POR_ESTADO_MAX = 30

BAIRROS_POR_CIDADE_MIN = 1
BAIRROS_POR_CIDADE_MAX = 5

CONDUTORES_MIN = 500
CONDUTORES_MAX = 800

VEICULOS_MIN = 200
VEICULOS_MAX = 500
VEICULOS_INATIVO_CHANCE = 1
VEICULOS_BLOQUEADO_CHANCE = 5

TRANSFERENCIA_CHANCE = 1

MULTAS_CHANCE = 5
MULTAS_20_CHANCE = 5
MULTAS_MIN = 1
MULTAS_MAX = 5